### ISSUE TITLE
GetHunter() error

### ISSUE THREAD

**Issue by monster010** [GamefreakDE/gmod_addons#4]
moin Gamefreak,

Wenn auf dem Server TTT Vote + TTT Totem nicht installiert ist, aber auf dem Client, entstehen scripterror

````
[ERROR] RunString:44: attempt to call method 'GetHunter' (a nil value)
  1. unknown - RunString:44
````

Wäre schön wenn du das fixen könntest =)

Mfg
monster010

**Comment by HagenKL** [comment]
Kann eigentlich nicht sein, da der Client immer die Server lua scripsts benutzt, sonst könnte man ja hacks mehr als einfach benutzen?

**Comment by monster010** [comment]
ich kann dir nur sagen was das problem ist was bei mir aufem server auftritt, wenn jemand mit dem addon aufen server joint
