### ISSUE TITLE
Randomat

### ISSUE THREAD

**Issue by monster010** [GamefreakDE/gmod_addons#5]
HeyHo Gamefreak,

wenn du nichts dagegen hast, würde ich den Randomat etwas abändern, so dass die Events nich mehr so nervig sind und manche (nur) eine begrenzte Zeit gehn, so wie es in der heutigen Folge (auch) vorgeschlagen wurde.

Mfg
monster010

**Comment by HagenKL** [comment]
Ich hab schon einige dinge geändert. Du kannst natürlich falls du willst noch dinge ändern.

**Comment by monster010** [comment]
Hab ich schon mitbekommen =), werd ma schauen was ich noch ändern
